name: sc_silenthill

on:
  workflow_dispatch:
  push:
    paths:
      - 'maps/sc_silenthill/**'
      - '.github/workflows/sc_silenthill.yml'

jobs:
  compile:
    uses: RaphaelIT7/SlashCo-Content/.github/workflows/map_compiler.yml@main
    secrets: inherit
    with:
      fastcompile: false
      createexportbsp: false
      debug: false
      map: "sc_silenthill"