name: sc_void_forest

on:
  workflow_dispatch:
  push:
    paths:
      - 'maps/sc_void_forest/**'

jobs:
  compile:
    uses: RaphaelIT7/SlashCo-Content/.github/workflows/map_compiler.yml@main
    secrets: inherit
    with:
      fastcompile: false
      createexportbsp: false
      debug: false
      map: "sc_void_forest"